CREATE PROCEDURE NETDESLIB.usp_InsertarCliente
(
	IN @IdCliente VARCHAR(36),
	IN @Nombres VARCHAR(250),
	IN @Apellidos VARCHAR(250),
	IN @Correo VARCHAR(250),
	IN @Edad INTEGER
)
LANGUAGE SQL



INSERT INTO NETDESLIB.CLIENTES
		(IDCLIENTE
		,NOMBRES
		,APELLIDOS
		,CORREO
		,EDAD)
	VALUES
		(@IDCLIENTE
		,@NOMBRES
		,@APELLIDOS
		,@CORREO
		,@EDAD)
