CREATE PROCEDURE NETDESLIB.USP_INSERTARPRODUCTO
(
	@IDPRODUCTO VARCHAR(36),
	@CODIGO INTEGER,
	@DESCRIPCION VARCHAR(250),
	@PRECIOUNITARIO DECIMAL(11,2)
)
LANGUAGE SQL

INSERT INTO NETDESLIB.PRODUCTO
		(IDPRODUCTO
		,CODIGO
		,DESCRIPCION
		,PRECIOUNITARIO)
	VALUES
		(@IDPRODUCTO
		,@CODIGO
		,@DESCRIPCION
		,@PRECIOUNITARIO)
