CREATE PROCEDURE NETDESLIB.USP_LISTARDETALLES
(
	@IDFACTURA VARCHAR(36)
)
LANGUAGE SQL
BEGIN

DECLARE C1 CURSOR FOR

SELECT IDFACTURADETALLE
		,IDFACTURACABECERA
		,PRODUCTO.DESCRIPCION
		,CANTIDAD
		,FACTURADETALLE.PRECIOUNITARIO
		,TOTAL
	FROM NETDESLIB.FACTURADETALLE
	INNER JOIN PRODUCTO ON FACTURADETALLE.IDPRODUCTO = PRODUCTO.IDPRODUCTO
	WHERE FACTURADETALLE.IDFACTURACABECERA = @IDFACTURA
	ORDER BY PRODUCTO.CODIGO;
	
	OPEN C1;
	
END
