CREATE PROCEDURE NETDESLIB.USP_LISTARFACTURAS
()
LANGUAGE SQL

BEGIN

DECLARE C1 CURSOR FOR
SELECT IDFACTURACABECERA
		,CLIENTES.NOMBRES || ' ' || CLIENTES.APELLIDOS AS CLIENTE
		,NUMERO
		,SERIE
		,FECHA
		,SUBTOTAL
		,IMPUESTOS
		,TOTAL
	FROM NETDESLIB.FACTURACABECERA
	INNER JOIN CLIENTES ON FACTURACABECERA.IDCLIENTE = CLIENTES.IDCLIENTE
	ORDER BY NUMERO;
	
OPEN C1;

END