CREATE PROCEDURE NETDESLIB.USP_INSERTARDETALLEFACTURA
(
	@IDFACTURADETALLE VARCHAR(36),
	@IDFACTURACABECERA VARCHAR(36),
	@IDPRODUCTO VARCHAR(36),
	@CANTIDAD INTEGER,
	@PRECIOUNITARIO DECIMAL,
	@TOTAL DECIMAL
)
LANGUAGE SQL

INSERT INTO NETDESLIB.FACTURADETALLE
		(IDFACTURADETALLE
		,IDFACTURACABECERA
		,IDPRODUCTO
		,CANTIDAD
		,PRECIOUNITARIO
		,TOTAL)	
	VALUES
		(@IDFACTURADETALLE
		,@IDFACTURACABECERA
		,@IDPRODUCTO
		,@CANTIDAD
		,@PRECIOUNITARIO
		,@TOTAL)