CREATE PROCEDURE USP_ACTUALIZARPRODUCTO
(
	@IDPRODUCTO VARCHAR(36),
	@CODIGO INTEGER,
	@DESCRIPCION VARCHAR(250),
	@PRECIOUNITARIO DECIMAL
)
LANGUAGE SQL

UPDATE NETDESLIB.PRODUCTO
	SET CODIGO = @CODIGO
		,DESCRIPCION = @DESCRIPCION
		,PRECIOUNITARIO = @PRECIOUNITARIO
	WHERE IDPRODUCTO = @IDPRODUCTO
