CREATE PROCEDURE NETDESLIB.USP_INSERTARFACTURA
(
	@IDFACTURACABECERA VARCHAR(36),
	@IDCLIENTE VARCHAR(36),
	@NUMERO INTEGER,
	@SERIE INTEGER,
	@FECHA DATE,
	@SUBTOTAL DECIMAL(11,2),
	@IMPUESTOS DECIMAL(11,2),
	@TOTAL DECIMAL(11,2)
)
LANGUAGE SQL

INSERT INTO NETDESLIB.FACTURACABECERA
		(IDFACTURACABECERA
		,IDCLIENTE
		,NUMERO
		,SERIE
		,FECHA
		,SUBTOTAL
		,IMPUESTOS
		,TOTAL)
	VALUES
		(@IDFACTURACABECERA
		,@IDCLIENTE
		,@NUMERO
		,@SERIE
		,@FECHA
		,@SUBTOTAL
		,@IMPUESTOS
		,@TOTAL)